from dataclasses import dataclass
from itertools import takewhile
from typing import List

from ecl_data_io.errors import ParsingError

from .record import Record
from .subparser import SubParser


class SingleKeywordSubParser(SubParser):
    def __init__(self, keyword):
        self._keyword = keyword

    @property
    def keyword(self):
        return self._keyword

    def parse(self, super_parser, lines):
        yield Record(self.keyword, None)


single_keywords = [
    "AIM",
    "AITS",
    "AITSOFF",
    "AJGRADNT",
    "ALKALINE",
    "API",
    "BIGMODEL",
    "BLACKOIL",
    "CART",
    "CIRCLE",
    "CO2STORE",
    "COAL",
    "COMPOFF",
    "DEADOIL",
    "DIAGDISP",
    "DIFFDP",
    "DIFFUSE",
    "DIMPLICIT",
    "DISGAS",
    "DPGRID",
    "DRAINAGE",
    "DSPDEINT",
    "DUALPERM",
    "DUALPORO",
    "DUMPFLUX",
    "E100NOSI",
    "ECHO",
    "ECLMC",
    "END",
    "ACTION",
    "ACTIONG",
    "ACTIONR",
    "ACTIONW",
    "ENDACTIO",
    "BOX",
    "ENDBOX",
    "DYNAMICR",
    "ENDDYN",
    "ENDFIN",
    "ENDINC",
    "EPSCHECK",
    "EXCEL",
    "FASTTRAC",
    "FIELD",
    "FILLEPS",
    "FIPOWG",
    "FMTHMD",
    "FMTIN",
    "FMTOUT",
    "FMTSAVE",
    "FOAM",
    "FREEZEPC",
    "FULLIMP",
    "FWELLS",
    "GADJUST",
    "GASBEGIN",
    "GASEND",
    "GASWAT",
    "GETGLOB",
    "GIMODEL",
    "GRAVDR",
    "GRAVDRB",
    "H2SSOL",
    "HALFTRAN",
    "HMPROPS",
    "HWELLS",
    "HYKR",
    "HYMOBGDR",
    "HYPC",
    "HYST",
    "HYSTJ",
    "HYSTK",
    "IKU3P",
    "IMPES",
    "IMPLICIT",
    "IMPSAT",
    "INIT",
    "INSPEC",
    "ISGAS",
    "KVALUES",
    "KVWI",
    "LAB",
    "LGRCOPY",
    "LIVEOIL",
    "LOWSALT",
    "LTRACE",
    "MEMSAVE",
    "METRIC",
    "MIXWPERM",
    "MONITOR",
    "MULTIN",
    "MULTIPHA",
    "MULTOUT",
    "MULTOUTS",
    "NARROW",
    "NEWTON",
    "NEWTRAN",
    "NINEPOIN",
    "NINEXZ",
    "NINEYZ",
    "NOAIMLGR",
    "NOCASC",
    "NOCIRCLE",
    "NODPCDT",
    "NODPCO",
    "NODPPM",
    "NOECHO",
    "NOFREEZE",
    "NOGGF",
    "NOHYKR",
    "NOHYPC",
    "NOHYST",
    "NOINSPEC",
    "NOLTRACE",
    "NOMIX",
    "NOMONITO",
    "NONNC",
    "NORSSPEC",
    "NOSIM",
    "NOWARN",
    "NOWARNEP",
    "ODD3P",
    "OFM",
    "OIL",
    "OLDEQUIL",
    "OLDTRAN",
    "OLDTRANR",
    "PEDERSEN",
    "PINCHOUT",
    "POLYMER",
    "PRCORR",
    "PSSTA",
    "PVT-M",
    "RADIAL",
    "RESOPT",
    "RKTRMDIR",
    "RPTISOL",
    "RPTONLY",
    "RPTONLYO",
    "RPTRUNSP",
    "RSM",
    "RSSPEC",
    "RUNSUM",
]
